server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

kafka:
  bootstrapServers: "localhost:9092"
  topic: "logs"
  acks: "all"
  lingerMs: 5
  retries: 3
